In [18]:
import tensorflow as tf
import keras

In [19]:
import numpy as np
from keras.models import Sequential
from keras.layers import Dense, Activation

In [20]:
data_in= np.array([[0,0],
                   [0,1],
                   [1,0],
                   [1,1]])

In [21]:
print(data_in)

[[0 0]
 [0 1]
 [1 0]
 [1 1]]


In [22]:
logic_and = np.array([[0],
                      [0],
                      [0],
                      [1]])

In [23]:
logic_or = np.array([[0],
                     [1],
                     [1],
                     [1]])

In [24]:
logic_xor = np.array([[0],
                      [1],
                      [1],
                      [0]])

In [70]:
model = keras.models.Sequential(layers=[
    keras.layers.Dense(input_dim = 2, units = 2), #2 inputs for logic gates
    keras.layers.Activation(keras.activations.sigmoid),
    keras.layers.Dense(units=1), #2 inputs for logic gates
    keras.layers.Activation(keras.activations.sigmoid)
])

model.compile(optimizer=keras.optimizers.SGD(lr=5), loss='mse') #lr=learning rate, loss or cost is mean squared error

In [78]:
#trains
model.fit(data_in, logic_xor, epochs=1000, verbose=False)

In [79]:
model.predict(np.array([[1,1]]))

array([[0.01016413]], dtype=float32)

In [71]:
keras.backend.eval(model.weights[0])

array([[ 1.1641029 , -0.30967242],
       [-1.1373607 , -0.9411906 ]], dtype=float32)